This is where it all begins...

diff --git a/bin/devops-sign-cert b/bin/devops-sign-cert
--- a/bin/devops-sign-cert
+++ b/bin/devops-sign-cert
@@ -13,33 +13,33 @@ VERBOSE=false
 
 while (( $# > 0 )); do
     case "${1}" in
-        --algorithm)
-            : "${2?✗ argument parsing failed: missing parameter for argument ‘${1}’}"
-            case "${2}" in
-                ED25519 | ED448 | RSA)
-                    PUBLIC_KEY_ALGORITHM=${2}
-                    shift 2
-                    ;;
-                *)
-                    echo "✗ argument parsing failed: acceptable values for ‘${1}’ are ED25519 | ED448 | RSA" 1>&2
-                    exit 1
-                    ;;
-            esac
+    --algorithm)
+        : "${2?✗ argument parsing failed: missing parameter for argument ‘${1}’}"
+        case "${2}" in
+        ED25519 | ED448 | RSA)
+            PUBLIC_KEY_ALGORITHM=${2}
+            shift 2
             ;;
-        --digest)
-            ENABLE_DIGEST=true
-            shift
+        *)
+            echo "✗ argument parsing failed: acceptable values for ‘${1}’ are ED25519 | ED448 | RSA" 1>&2
+            exit 1
             ;;
-        --strict)
-            STRICT_VERIFICATION=true
-            shift
-            ;;
-        --verbose)
-            VERBOSE=true
-            shift
-            ;;
-        -h | --help)
-            cat << EOF
+        esac
+        ;;
+    --digest)
+        ENABLE_DIGEST=true
+        shift
+        ;;
+    --strict)
+        STRICT_VERIFICATION=true
+        shift
+        ;;
+    --verbose)
+        VERBOSE=true
+        shift
+        ;;
+    -h | --help)
+        cat << EOF
 Usage:
     ${0##*/} [OPTION]... CERT_NAME
 
@@ -61,21 +61,21 @@ Positional arguments:
     CERT_NAME
         common name of the end certificate to be generated
 EOF
-            shift
-            exit
-            ;;
-        -v | --version)
-            echo v0.1.0
-            shift
-            exit
-            ;;
-        --)
-            shift
-            break
-            ;;
-        *)
-            break
-            ;;
+        shift
+        exit
+        ;;
+    -v | --version)
+        echo v0.1.0
+        shift
+        exit
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        break
+        ;;
     esac
 done
 
@@ -175,13 +175,17 @@ fi
 
 # [ Intermediate CA ]
 
-if [ "${PUBLIC_KEY_ALGORITHM}" = ED25519 ]; then
+case "${PUBLIC_KEY_ALGORITHM}" in
+ED25519)
     openssl genpkey -algorithm "${PUBLIC_KEY_ALGORITHM}" -out interm.key
-elif [ "${PUBLIC_KEY_ALGORITHM}" = ED448 ]; then
+    ;;
+ED448)
     openssl genpkey -algorithm "${PUBLIC_KEY_ALGORITHM}" -out interm.key
-else
+    ;;
+*)
     openssl genpkey -algorithm "${PUBLIC_KEY_ALGORITHM}" -out interm.key -pkeyopt rsa_keygen_bits:4096
-fi
+    ;;
+esac
 
 openssl req \
     -new \
diff --git a/bin/domain-inspect b/bin/domain-inspect
--- a/bin/domain-inspect
+++ b/bin/domain-inspect
@@ -8,8 +8,8 @@ trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
 
 while (( $# > 0 )); do
     case "${1}" in
-        -h | --help)
-            cat << EOF
+    -h | --help)
+        cat << EOF
 Usage:
     ${0##*/} [OPTION]... MANIFEST DOMAIN...
 
@@ -25,33 +25,33 @@ Positional arguments:
     DOMAIN
         domain name to be queried
 EOF
-            shift
-            exit
-            ;;
-        -v | --version)
-            echo v0.1.0
-            shift
-            exit
-            ;;
-        --)
-            shift
-            break
-            ;;
-        *)
-            break
-            ;;
+        shift
+        exit
+        ;;
+    -v | --version)
+        echo v0.1.0
+        shift
+        exit
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        break
+        ;;
     esac
 done
 
 : "${1?✗ argument parsing failed: missing positional argument ‘MANIFEST’}"
 case "${1}" in
-    authority | whois)
-        MANIFEST=${1}
-        ;;
-    *)
-        echo "✗ argument parsing failed: acceptable values for ‘MANIFEST’ are authority | whois" 1>&2
-        exit 1
-        ;;
+authority | whois)
+    MANIFEST=${1}
+    ;;
+*)
+    echo "✗ argument parsing failed: acceptable values for ‘MANIFEST’ are authority | whois" 1>&2
+    exit 1
+    ;;
 esac
 shift
 
diff --git a/bin/network-dns-hall b/bin/network-dns-hall
--- a/bin/network-dns-hall
+++ b/bin/network-dns-hall
@@ -8,8 +8,8 @@ trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
 
 while (( $# > 0 )); do
     case "${1}" in
-        -h | --help)
-            cat << EOF
+    -h | --help)
+        cat << EOF
 Usage:
     ${0##*/} [OPTION]... VENDOR
 
@@ -23,33 +23,33 @@ Positional arguments:
     VENDOR (cloudflare | opendns | quad9)
         dns vendor name
 EOF
-            shift
-            exit
-            ;;
-        -v | --version)
-            echo v0.1.0
-            shift
-            exit
-            ;;
-        --)
-            shift
-            break
-            ;;
-        *)
-            break
-            ;;
+        shift
+        exit
+        ;;
+    -v | --version)
+        echo v0.1.0
+        shift
+        exit
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        break
+        ;;
     esac
 done
 
 : "${1?✗ argument parsing failed: missing positional argument ‘VENDOR’}"
 case "${1}" in
-    cloudflare | opendns | quad9)
-        VENDOR=${1}
-        ;;
-    *)
-        echo "✗ argument parsing failed: acceptable values for ‘VENDOR’ are cloudflare | opendns | quad9" 1>&2
-        exit 1
-        ;;
+cloudflare | opendns | quad9)
+    VENDOR=${1}
+    ;;
+*)
+    echo "✗ argument parsing failed: acceptable values for ‘VENDOR’ are cloudflare | opendns | quad9" 1>&2
+    exit 1
+    ;;
 esac
 shift
 
@@ -58,20 +58,24 @@ if (( $# > 0 )); then
     exit 1
 fi
 
-if [ "${VENDOR}" = cloudflare ]; then
+case "${VENDOR}" in
+cloudflare)
     dig \
         1dot1dot1dot1.cloudflare-dns.com a 1dot1dot1dot1.cloudflare-dns.com aaaa \
         +short
-elif [ "${VENDOR}" = opendns ]; then
+    ;;
+opendns)
     dig \
         resolver1.opendns.com a resolver1.opendns.com aaaa \
         resolver2.opendns.com a resolver2.opendns.com aaaa \
         resolver3.opendns.com a resolver3.opendns.com aaaa \
         resolver4.opendns.com a resolver4.opendns.com aaaa \
         +short
-else
+    ;;
+*)
     dig \
         dns.quad9.net a dns.quad9.net aaaa \
         dns-nosec.quad9.net a dns-nosec.quad9.net aaaa \
         +short
-fi
+    ;;
+esac
diff --git a/bin/sys-info b/bin/sys-info
--- a/bin/sys-info
+++ b/bin/sys-info
@@ -8,8 +8,8 @@ trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
 
 while (( $# > 0 )); do
     case "${1}" in
-        -h | --help)
-            cat << EOF
+    -h | --help)
+        cat << EOF
 Usage:
     ${0##*/} [OPTION]... MANIFEST
 
@@ -23,33 +23,33 @@ Positional arguments:
     MANIFEST (distro | group | user)
         manifest name
 EOF
-            shift
-            exit
-            ;;
-        -v | --version)
-            echo v0.1.0
-            shift
-            exit
-            ;;
-        --)
-            shift
-            break
-            ;;
-        *)
-            break
-            ;;
+        shift
+        exit
+        ;;
+    -v | --version)
+        echo v0.1.0
+        shift
+        exit
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        break
+        ;;
     esac
 done
 
 : "${1?✗ argument parsing failed: missing positional argument ‘MANIFEST’}"
 case "${1}" in
-    distro | group | user)
-        MANIFEST=${1}
-        ;;
-    *)
-        echo "✗ argument parsing failed: acceptable values for ‘MANIFEST’ are distro | group | user" 1>&2
-        exit 1
-        ;;
+distro | group | user)
+    MANIFEST=${1}
+    ;;
+*)
+    echo "✗ argument parsing failed: acceptable values for ‘MANIFEST’ are distro | group | user" 1>&2
+    exit 1
+    ;;
 esac
 shift
 
@@ -58,12 +58,14 @@ if (( $# > 0 )); then
     exit 1
 fi
 
-if [ "${MANIFEST}" = distro ]; then
+case "${MANIFEST}" in
+distro)
     # shellcheck disable=SC1090
     source <(grep '^ID=' /etc/os-release)
     DISTRO=${ID:-linux}
     echo "${DISTRO}"
-elif [ "${MANIFEST}" = group ]; then
+    ;;
+group)
     sort \
         --field-separator : \
         --key 3,3n \
@@ -77,7 +79,8 @@ elif [ "${MANIFEST}" = group ]; then
         --separator : \
         --table \
         --table-columns 'GROUP_NAME,GID,USER_LIST'
-else
+    ;;
+*)
     sort \
         --field-separator : \
         --key 3,3n \
@@ -91,4 +94,5 @@ else
         --separator : \
         --table \
         --table-columns 'LOGIN_NAME,UID,GID,COMMENT,HOME,SHELL'
-fi
+    ;;
+esac
diff --git a/sbin/letsencrypt-provision b/sbin/letsencrypt-provision
--- a/sbin/letsencrypt-provision
+++ b/sbin/letsencrypt-provision
@@ -13,8 +13,8 @@ fi
 
 while (( $# > 0 )); do
     case "${1}" in
-        -h | --help)
-            cat << EOF
+    -h | --help)
+        cat << EOF
 Usage:
     ${0##*/} [OPTION]... MODE DOMAIN
 
@@ -30,33 +30,33 @@ Positional arguments:
     DOMAIN
         domain name to apply
 EOF
-            shift
-            exit
-            ;;
-        -v | --version)
-            echo v0.1.0
-            shift
-            exit
-            ;;
-        --)
-            shift
-            break
-            ;;
-        *)
-            break
-            ;;
+        shift
+        exit
+        ;;
+    -v | --version)
+        echo v0.1.0
+        shift
+        exit
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        break
+        ;;
     esac
 done
 
 : "${1?✗ argument parsing failed: missing positional argument ‘MODE’}"
 case "${1}" in
-    request | revoke)
-        MODE=${1}
-        ;;
-    *)
-        echo "✗ argument parsing failed: acceptable values for ‘MODE’ are request | revoke" 1>&2
-        exit 1
-        ;;
+request | revoke)
+    MODE=${1}
+    ;;
+*)
+    echo "✗ argument parsing failed: acceptable values for ‘MODE’ are request | revoke" 1>&2
+    exit 1
+    ;;
 esac
 DOMAIN=${2?✗ argument parsing failed: missing positional argument ‘DOMAIN’}
 shift 2
diff --git a/sbin/sys-quick b/sbin/sys-quick
--- a/sbin/sys-quick
+++ b/sbin/sys-quick
@@ -13,8 +13,8 @@ fi
 
 while (( $# > 0 )); do
     case "${1}" in
-        -h | --help)
-            cat << EOF
+    -h | --help)
+        cat << EOF
 Usage:
     ${0##*/} [OPTION]... ALIAS
 
@@ -28,33 +28,33 @@ Positional arguments:
     ALIAS (netstat | iptables | ip6tables | ss)
         diagnostic launcher name
 EOF
-            shift
-            exit
-            ;;
-        -v | --version)
-            echo v0.1.0
-            shift
-            exit
-            ;;
-        --)
-            shift
-            break
-            ;;
-        *)
-            break
-            ;;
+        shift
+        exit
+        ;;
+    -v | --version)
+        echo v0.1.0
+        shift
+        exit
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        break
+        ;;
     esac
 done
 
 : "${1?✗ argument parsing failed: missing positional argument ‘ALIAS’}"
 case "${1}" in
-    netstat | iptables | ip6tables | ss)
-        ALIAS=${1}
-        ;;
-    *)
-        echo "✗ argument parsing failed: acceptable values for ‘ALIAS’ are netstat | iptables | ip6tables | ss" 1>&2
-        exit 1
-        ;;
+netstat | iptables | ip6tables | ss)
+    ALIAS=${1}
+    ;;
+*)
+    echo "✗ argument parsing failed: acceptable values for ‘ALIAS’ are netstat | iptables | ip6tables | ss" 1>&2
+    exit 1
+    ;;
 esac
 shift
 
@@ -65,16 +65,21 @@ fi
 
 separator=----------------------------------------------------------------
 
-if [ "${ALIAS}" = netstat ]; then
+case "${ALIAS}" in
+netstat)
     netstat --tcp --udp --raw --listening --numeric --programs
-elif [ "${ALIAS}" = iptables ]; then
+    ;;
+iptables)
     iptables --table filter --list --numeric --verbose --line-numbers
     printf '\n%s\n\n' "${separator}"
     iptables --table nat --list --numeric --verbose --line-numbers
-elif [ "${ALIAS}" = ip6tables ]; then
+    ;;
+ip6tables)
     ip6tables --table filter --list --numeric --verbose --line-numbers
     printf '\n%s\n\n' "${separator}"
     ip6tables --table nat --list --numeric --verbose --line-numbers
-else
+    ;;
+*)
     ss --tcp --udp --raw --listening --numeric --processes
-fi
+    ;;
+esac
