This is where it all begins...

diff --git a/bin/devops-sign-cert b/bin/devops-sign-cert
--- a/bin/devops-sign-cert
+++ b/bin/devops-sign-cert
@@ -1,44 +1,76 @@
 #!/bin/bash
 
+set -o errexit
+set -o nounset
+set -o pipefail
+
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+
+PUBLIC_KEY_ALGORITHM=RSA
+ENABLE_DIGEST=false
+STRICT_VERIFICATION=false
+VERBOSE=false
+
 while (( $# > 0 )); do
     case "${1}" in
+        --algorithm)
+            case "${2}" in
+                ED25519 | ED448 | RSA)
+                    PUBLIC_KEY_ALGORITHM="${2}"
+                    shift 2
+                    ;;
+                *)
+                    echo "✗ argument parsing failed: acceptable values for ‘${1}’ are ED25519 | ED448 | RSA" 1>&2
+                    exit 1
+                    ;;
+            esac
+            ;;
         --digest)
-            DIGEST=true
-            shift
-            ;;
-        --ed25519)
-            ED25519=true
-            shift
-            ;;
-        --ed448)
-            ED448=true
-            shift
-            ;;
-        --inspect)
-            INSPECT=true
+            ENABLE_DIGEST=true
             shift
             ;;
         --strict)
-            STRICT=true
+            STRICT_VERIFICATION=true
             shift
+            ;;
+        --verbose)
+            VERBOSE=true
+            shift
+            ;;
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]... CERT_NAME
+
+Optional arguments:
+    --algorithm
+        use the specified public key algorithm (ED25519 | ED448 | RSA)
+    --digest
+        enable digest
+    --strict
+        enable strict verification
+    --verbose
+        enable verbose inspection
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+
+Positional arguments:
+    CERT_NAME
+        common name of the end certificate to be generated
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
             ;;
         --)
             shift
             break
-            ;;
-        --help)
-            cat << EOF
-Usage:
-    ${0##*/} [options] COMMON_NAME
-
-Options:
-    --digest
-    --ed25519
-    --ed448
-    --inspect
-    --strict
-EOF
-            exit
             ;;
         *)
             break
@@ -46,8 +78,12 @@ EOF
     esac
 done
 
-if (( $# != 1 )); then
-    exit
+CERT_NAME=${1?✗ argument parsing failed: missing positional argument ‘CERT_NAME’}
+shift
+
+if (( $# > 0 )); then
+    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
+    exit 1
 fi
 
 digest () {
@@ -128,22 +164,22 @@ openssl x509 \
     -sha512 \
     -out ca.csr
 
-if [ "${INSPECT}" = 'true' ]; then
-    inspect ca
+if [ "${ENABLE_DIGEST}" = true ]; then
+    digest ca
 fi
 
-if [ "${DIGEST}" = 'true' ]; then
-    digest ca
+if [ "${VERBOSE}" = true ]; then
+    inspect ca
 fi
 
 # [ Intermediate CA ]
 
-if [ "${ED25519}" = 'true' ]; then
-    openssl genpkey -algorithm ED25519 -out interm.key
-elif [ "${ED448}" = 'true' ]; then
-    openssl genpkey -algorithm ED448 -out interm.key
+if [ "${PUBLIC_KEY_ALGORITHM}" = ED25519 ]; then
+    openssl genpkey -algorithm "${PUBLIC_KEY_ALGORITHM}" -out interm.key
+elif [ "${PUBLIC_KEY_ALGORITHM}" = ED448 ]; then
+    openssl genpkey -algorithm "${PUBLIC_KEY_ALGORITHM}" -out interm.key
 else
-    openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out interm.key
+    openssl genpkey -algorithm "${PUBLIC_KEY_ALGORITHM}" -out interm.key -pkeyopt rsa_keygen_bits:4096
 fi
 
 openssl req \
@@ -181,46 +217,46 @@ subjectKeyIdentifier=hash
 authorityKeyIdentifier=keyid:always,issuer
 EOF
 
-if [ "${INSPECT}" = 'true' ]; then
-    inspect interm
+if [ "${ENABLE_DIGEST}" = true ]; then
+    digest interm
 fi
 
-if [ "${DIGEST}" = 'true' ]; then
-    digest interm
+if [ "${VERBOSE}" = true ]; then
+    inspect interm
 fi
 
 # [ End Entity ]
 
-#openssl genrsa -out "${1}".key 4096
-openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out "${1}".key
+#openssl genrsa -out "${CERT_NAME}".key 4096
+openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out "${CERT_NAME}".key
 openssl req \
     -new \
-    -key "${1}".key \
+    -key "${CERT_NAME}".key \
     -sha512 \
-    -subj "/O=Privacy Guard/OU=Public Key Infrastructure/CN=${1}" \
+    -subj "/O=Privacy Guard/OU=Public Key Infrastructure/CN=${CERT_NAME}" \
     -addext 'subjectAltName=DNS:localhost,IP:127.0.0.1,IP:::1' \
-    -out "${1}".csr
+    -out "${CERT_NAME}".csr
 
 #openssl req \
 #    -new \
-#    -newkey rsa -pkeyopt rsa_keygen_bits:4096 -nodes -keyout "${1}".key \
+#    -newkey rsa -pkeyopt rsa_keygen_bits:4096 -nodes -keyout "${CERT_NAME}".key \
 #    -sha512 \
-#    -subj "/O=Privacy Guard/OU=Public Key Infrastructure/CN=${1}" \
+#    -subj "/O=Privacy Guard/OU=Public Key Infrastructure/CN=${CERT_NAME}" \
 #    -addext 'subjectAltName=DNS:localhost,IP:127.0.0.1,IP:::1' \
-#    -out "${1}".csr
+#    -out "${CERT_NAME}".csr
 
-openssl pkey -pubout -in "${1}".key -out "${1}".pub
+openssl pkey -pubout -in "${CERT_NAME}".key -out "${CERT_NAME}".pub
 
 openssl x509 \
     -req \
     -CA interm.crt -CAkey interm.key \
     -CAcreateserial \
     -sha512 \
-    -in "${1}".csr \
+    -in "${CERT_NAME}".csr \
     -days 825 \
     -extfile - \
     -extensions end_entity \
-    -out "${1}".crt \
+    -out "${CERT_NAME}".crt \
     << 'EOF'
 [ end_entity ]
 basicConstraints=critical,CA:FALSE
@@ -230,24 +266,24 @@ authorityKeyIdentifier=keyid,issuer
 subjectAltName=DNS:localhost,IP:127.0.0.1,IP:::1
 EOF
 
-if [ "${INSPECT}" = 'true' ]; then
-    inspect "${1}"
+if [ "${ENABLE_DIGEST}" = true ]; then
+    digest "${CERT_NAME}"
 fi
 
-if [ "${DIGEST}" = 'true' ]; then
-    digest "${1}"
+if [ "${VERBOSE}" = true ]; then
+    inspect "${CERT_NAME}"
 fi
 
 # [ Chain of Trust ]
 
-cat "${1}".crt interm.crt | tee chain.crt &> /dev/null
+cat "${CERT_NAME}".crt interm.crt | tee chain.crt &> /dev/null
 
-if [ "${STRICT}" = 'true' ]; then
+if [ "${STRICT_VERIFICATION}" = true ]; then
     echo '+--'
     openssl verify -CAfile ca.crt -no-CApath -show_chain ca.crt
     openssl verify -CAfile ca.crt -no-CApath -show_chain interm.crt
-    openssl verify -CAfile ca.crt -no-CApath -untrusted interm.crt -show_chain "${1}".crt
+    openssl verify -CAfile ca.crt -no-CApath -show_chain -untrusted interm.crt "${CERT_NAME}".crt
     echo '--+'
 fi
 
-openssl verify -CAfile ca.crt -no-CApath -untrusted interm.crt -show_chain chain.crt
+openssl verify -CAfile ca.crt -no-CApath -show_chain -untrusted interm.crt chain.crt
diff --git a/bin/digitalocean-delete-record b/bin/digitalocean-delete-record
--- a/bin/digitalocean-delete-record
+++ b/bin/digitalocean-delete-record
@@ -1,9 +1,58 @@
 #!/bin/bash
 
+set -o errexit
+set -o nounset
+set -o pipefail
+
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+
 # shellcheck disable=SC1090
 source "$(dirname "$(dirname "$(realpath "${0}")")")/.privacy/digitalocean.cfg"
 
+while (( $# > 0 )); do
+    case "${1}" in
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]... RECORD
+
+Optional arguments:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+
+Positional arguments:
+    RECORD
+        dns record identifier
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+RECORD=${1?✗ argument parsing failed: missing positional argument ‘RECORD’}
+shift
+
+if (( $# > 0 )); then
+    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
+    exit 1
+fi
+
 curl --fail --location --silent --show-error --request DELETE \
     --header "Authorization: Bearer ${AUTH_TOKEN}" \
-    "https://api.digitalocean.com/v2/domains/${DOMAIN}/records/${1}" \
+    "https://api.digitalocean.com/v2/domains/${DOMAIN}/records/${RECORD}" \
     | python3 -m json.tool
diff --git a/bin/namecheap-domain-watch b/bin/namecheap-domain-watch
--- a/bin/namecheap-domain-watch
+++ b/bin/namecheap-domain-watch
@@ -4,8 +4,46 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+
 # shellcheck disable=SC1090
 source "$(dirname "$(dirname "$(realpath "${0}")")")/.privacy/namecheap.cfg"
+
+while (( $# > 0 )); do
+    case "${1}" in
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]...
+
+Optional arguments:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+if (( $# > 0 )); then
+    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
+    exit 1
+fi
 
 sleep 15
 
@@ -13,8 +51,14 @@ CURRENCY_RATE=$(curl --fail --location --silent --show-error --request GET "http
 PUBLIC_IP_ADDRESS=$(dig myip.opendns.com @208.67.222.222 a +short)
 REQUEST_API_METHOD='namecheap.users.getPricing'
 
-if [ -z "${CURRENCY_RATE}" ] || [ -z "${PUBLIC_IP_ADDRESS}" ]; then
-    exit
+if [ -z "${CURRENCY_RATE}" ]; then
+    echo "✗ unexpected error: cannot acquire the currency rate" 1>&2
+    exit 1
+fi
+
+if [ -z "${PUBLIC_IP_ADDRESS}" ]; then
+    echo "✗ unexpected error: cannot resolve the public ip address" 1>&2
+    exit 1
 fi
 
 for i in ${WATCH_LIST}; do
diff --git a/bin/network-dns-perf b/bin/network-dns-perf
--- a/bin/network-dns-perf
+++ b/bin/network-dns-perf
@@ -1,14 +1,39 @@
 #!/bin/bash
 
+set -o errexit
+set -o nounset
+set -o pipefail
+
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+
+COUNT=64
+
 while (( $# > 0 )); do
     case "${1}" in
-        -c|--count)
-            if [ -z "${2}" ]; then
-                echo "✗ option takes an argument: ‘${1}’" 1>&2
-                exit 1
-            fi
-            COUNT=${2}
+        -c | --count)
+            COUNT=${2?✗ argument parsing failed: missing parameter for argument ‘${1}’}
             shift 2
+            ;;
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]...
+
+Optional arguments:
+    -c, --count
+        number of request packets to send
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
             ;;
         --)
             shift
@@ -21,11 +46,9 @@ while (( $# > 0 )); do
 done
 
 if (( $# > 0 )); then
-    echo "✗ unrecognized parameter: ‘${1}’" 1>&2
+    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
     exit 1
 fi
-
-: "${COUNT:=64}"
 
 NAMESERVER=$(awk '/nameserver/ { print $2 }' /etc/resolv.conf)
 
diff --git a/bin/site-gen-icon b/bin/site-gen-icon
--- a/bin/site-gen-icon
+++ b/bin/site-gen-icon
@@ -1,11 +1,57 @@
 #!/bin/bash
 
-if (( $# != 1 )); then
-    exit
+set -o errexit
+set -o nounset
+set -o pipefail
+
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+
+while (( $# > 0 )); do
+    case "${1}" in
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]... INPUT_IMAGE
+
+Optional arguments:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+
+Positional arguments:
+    INPUT_IMAGE
+        input image to be converted
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+INPUT_IMAGE=${1?✗ argument parsing failed: missing positional argument ‘INPUT_IMAGE’}
+shift
+
+if (( $# > 0 )); then
+    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
+    exit 1
 fi
 
-if [ ! -f "${1}" ]; then
-    exit
+if [ ! -f "${INPUT_IMAGE}" ]; then
+    echo "✗ not a regular file: ‘${INPUT_IMAGE}’" 1>&2
+    exit 1
 fi
 
-convert -background transparent "${1}" -define icon:auto-resize=16,32 favicon.ico
+convert -background transparent "${INPUT_IMAGE}" -define icon:auto-resize=16,32 favicon.ico
diff --git a/bin/slack-clean-stream b/bin/slack-clean-stream
--- a/bin/slack-clean-stream
+++ b/bin/slack-clean-stream
@@ -1,9 +1,53 @@
 #!/bin/bash
 
+set -o errexit
+set -o nounset
+set -o pipefail
+
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+
 # shellcheck disable=SC1090
 source "$(dirname "$(dirname "$(realpath "${0}")")")/.privacy/slack.cfg"
 
-export MESSAGE_RETENTION=${MESSAGE_RETENTION:=86400}
+: "${MESSAGE_RETENTION:=86400}"
+
+while (( $# > 0 )); do
+    case "${1}" in
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]...
+
+Optional arguments:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+export MESSAGE_RETENTION
+
+if (( $# > 0 )); then
+    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
+    exit 1
+fi
 
 list=$(curl --fail --location --silent --show-error --request GET \
     --header "Authorization: Bearer ${TOKEN}" \
diff --git a/bin/slack-push-message b/bin/slack-push-message
--- a/bin/slack-push-message
+++ b/bin/slack-push-message
@@ -1,7 +1,49 @@
 #!/bin/bash
 
+set -o errexit
+set -o nounset
+set -o pipefail
+
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+
 # shellcheck disable=SC1090
 source "$(dirname "$(dirname "$(realpath "${0}")")")/.privacy/slack.cfg"
+
+while (( $# > 0 )); do
+    case "${1}" in
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]...
+
+Optional arguments:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+if (( $# > 0 )); then
+    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
+    exit 1
+fi
 
 TEXT=''
 while IFS='' read -r LINE; do
diff --git a/bin/swaks-push-message b/bin/swaks-push-message
--- a/bin/swaks-push-message
+++ b/bin/swaks-push-message
@@ -1,11 +1,53 @@
 #!/bin/bash
 
-if (( $# == 0 )); then
-    exit
-fi
+set -o errexit
+set -o nounset
+set -o pipefail
+
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
 
 # shellcheck disable=SC1090
 source "$(dirname "$(dirname "$(realpath "${0}")")")/.privacy/smtp.cfg"
+
+while (( $# > 0 )); do
+    case "${1}" in
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]... COMMAND...
+
+Optional arguments:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+
+Positional arguments:
+    COMMAND
+        command to be executed within command substitution
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+if (( $# == 0 )); then
+    echo "✗ argument parsing failed: missing positional argument ‘COMMAND’" 1>&2
+    exit 1
+fi
 
 # Swiss Army Knife SMTP
 
diff --git a/sbin/docker-deploy-node-exporter b/sbin/docker-deploy-node-exporter
--- a/sbin/docker-deploy-node-exporter
+++ b/sbin/docker-deploy-node-exporter
@@ -1,11 +1,53 @@
 #!/bin/bash
 
+set -o errexit
+set -o nounset
+set -o pipefail
+
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+
 if (( EUID != 0 )); then
     echo "✗ This script must be run as root" 1>&2
     exit 1
 fi
 
-NAME='node-exporter'
+while (( $# > 0 )); do
+    case "${1}" in
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]...
+
+Optional arguments:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+if (( $# > 0 )); then
+    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
+    exit 1
+fi
+
+NAME=node-exporter
 
 if [ -n "$(docker container ls --all --filter name='^/'${NAME}'$' --format '.')" ]; then
     docker container stop "${NAME}"
diff --git a/sbin/letsencrypt-request-cert b/sbin/letsencrypt-request-cert
--- a/sbin/letsencrypt-request-cert
+++ b/sbin/letsencrypt-request-cert
@@ -1,12 +1,61 @@
 #!/bin/bash
 
+set -o errexit
+set -o nounset
+set -o pipefail
+
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+
 if (( EUID != 0 )); then
     echo "✗ This script must be run as root" 1>&2
     exit 1
 fi
 
+while (( $# > 0 )); do
+    case "${1}" in
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]... DOMAIN
+
+Optional arguments:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+
+Positional arguments:
+    DOMAIN
+        domain name to apply
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+DOMAIN=${1?✗ argument parsing failed: missing positional argument ‘DOMAIN’}
+shift
+
+if (( $# > 0 )); then
+    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
+    exit 1
+fi
+
 certbot certonly \
-    --domains "${1}" \
+    --domains "${DOMAIN}" \
     --manual \
     --manual-public-ip-logging-ok \
     --preferred-challenges dns \
diff --git a/sbin/sys-obs b/sbin/sys-obs
--- a/sbin/sys-obs
+++ b/sbin/sys-obs
@@ -1,7 +1,49 @@
 #!/bin/bash
 
+set -o errexit
+set -o nounset
+set -o pipefail
+
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+
 if (( EUID != 0 )); then
     echo "✗ This script must be run as root" 1>&2
+    exit 1
+fi
+
+while (( $# > 0 )); do
+    case "${1}" in
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]...
+
+Optional arguments:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+if (( $# > 0 )); then
+    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
     exit 1
 fi
 
@@ -17,8 +59,8 @@ DISTRO=${ID:-linux}
 case "${DISTRO}" in
     arch | manjaro)
         echo '------ [ package ] ------'
-        pacman --query --foreign | sed 's/$/ [foreign]/g' | column -t
-        pacman --query --deps --unrequired | sed 's/$/ [orphan]/g' | column -t
+        pacman --query --foreign || true | sed 's/$/ [foreign]/g' | column -t
+        pacman --query --deps --unrequired || true | sed 's/$/ [orphan]/g' | column -t
         echo '------ [ configuration ] ------'
         find /etc -type f -iregex '.+\.\(old\|pac\(new\|save\)\)' -print0 | sort --zero-terminated | tr '\0' '\n'
         ;;
@@ -32,8 +74,8 @@ case "${DISTRO}" in
         ;;
     kali | ubuntu)
         echo '------ [ package ] ------'
-        apt list 2> /dev/null | grep '\<\(local\|residual-config\)\]' | column -t
-        apt search '\<(dummy|transitional)\>' 2> /dev/null | grep '\[installed\>' | column -t
+        apt list 2> /dev/null | grep '\<\(local\|residual-config\)\]' || true | column -t
+        apt search '\<(dummy|transitional)\>' 2> /dev/null | grep '\[installed\>' || true | column -t
         echo '------ [ configuration ] ------'
         find /etc -type f \( -iregex '.+\.dpkg-\(dist\|new\|old\)' -o -iregex '.+\.old' -o -iregex '.+\.ucf-\(dist\|new\|old\)' \) -print0 | sort --zero-terminated | tr '\0' '\n'
         dpkg-query --show --showformat '${Package}\n${Conffiles}\n' | awk '/^[^ ]/{pkg=$1}/ obsolete$/{print pkg,$0}' | column -t
diff --git a/sbin/sys-sync b/sbin/sys-sync
--- a/sbin/sys-sync
+++ b/sbin/sys-sync
@@ -1,15 +1,44 @@
 #!/bin/bash
 
+set -o errexit
+set -o nounset
+set -o pipefail
+
+trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+
 if (( EUID != 0 )); then
     echo "✗ This script must be run as root" 1>&2
     exit 1
 fi
 
+FORCE_SYNC=false
+
 while (( $# > 0 )); do
     case "${1}" in
-        -f|--force)
+        -f | --force)
             FORCE_SYNC=true
             shift
+            ;;
+        -h | --help)
+            cat << EOF
+Usage:
+    ${0##*/} [OPTION]...
+
+Optional arguments:
+    -f, --force
+        force synchronization of package metadata
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+            shift
+            exit
+            ;;
+        -v | --version)
+            echo v0.1.0
+            shift
+            exit
             ;;
         --)
             shift
@@ -22,7 +51,7 @@ while (( $# > 0 )); do
 done
 
 if (( $# > 0 )); then
-    echo "✗ unrecognized parameter: ‘${1}’" 1>&2
+    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
     exit 1
 fi
 
@@ -48,7 +77,7 @@ case "${DISTRO}" in
             dnf clean all
         fi
         dnf makecache
-        dnf check-update --changelogs
+        dnf check-update --changelogs || true
         dnf upgrade
         dnf autoremove
         dnf clean packages
