This is where it all begins...

diff --git a/bin/devops-sign-cert b/bin/devops-sign-cert
--- a/bin/devops-sign-cert
+++ b/bin/devops-sign-cert
@@ -1,10 +1,52 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
+    ${0##*/} [OPTION]... CERT_NAME
+
+Options:
+    --algorithm ALGORITHM (ED25519 | ED448 | RSA)
+        use the specified public key algorithm (default: RSA)
+    --digest
+        enable digest (default: false)
+    --strict
+        enable strict verification (default: false)
+    --verbose
+        enable verbose inspection (default: false)
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+
+Arguments:
+    CERT_NAME
+        common name of the end certificate to be generated
+EOF
+}
 
 PUBLIC_KEY_ALGORITHM=RSA
 ENABLE_DIGEST=false
@@ -14,15 +56,14 @@ VERBOSE=false
 while (( $# > 0 )); do
     case ${1} in
     --algorithm)
-        : "${2?✗ argument parsing failed: missing parameter for argument ‘${1}’}"
+        : "${2?✗ option parsing failed: missing value for ‘${1}’}"
         case ${2} in
         ED25519 | ED448 | RSA)
             PUBLIC_KEY_ALGORITHM=${2}
             shift 2
             ;;
         *)
-            echo "✗ argument parsing failed: acceptable values for ‘${1}’ are ED25519 | ED448 | RSA" 1>&2
-            exit 1
+            die "✗ option parsing failed: acceptable values for ‘${1}’ are ED25519 | ED448 | RSA"
             ;;
         esac
         ;;
@@ -39,28 +80,7 @@ while (( $# > 0 )); do
         shift
         ;;
     -h | --help)
-        cat << EOF
-Usage:
-    ${0##*/} [OPTION]... CERT_NAME
-
-Optional arguments:
-    --algorithm ALGORITHM (ED25519 | ED448 | RSA)
-        use the specified public key algorithm (default: RSA)
-    --digest
-        enable digest (default: false)
-    --strict
-        enable strict verification (default: false)
-    --verbose
-        enable verbose inspection (default: false)
-    -h, --help
-        show this help message and exit
-    -v, --version
-        output version information and exit
-
-Positional arguments:
-    CERT_NAME
-        common name of the end certificate to be generated
-EOF
+        display_help
         shift
         exit
         ;;
@@ -79,13 +99,18 @@ EOF
     esac
 done
 
-CERT_NAME=${1?✗ argument parsing failed: missing positional argument ‘CERT_NAME’}
+CERT_NAME=${1?✗ argument parsing failed: missing argument ‘CERT_NAME’}
 shift
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 digest () {
     echo '+--'
diff --git a/bin/digitalocean-delete-record b/bin/digitalocean-delete-record
--- a/bin/digitalocean-delete-record
+++ b/bin/digitalocean-delete-record
@@ -1,10 +1,44 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
+    ${0##*/} [OPTION]... RECORD
+
+Options:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+
+Arguments:
+    RECORD
+        dns record identifier
+EOF
+}
 
 # shellcheck disable=SC1090
 source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.privacy/digitalocean.cfg"
@@ -12,20 +46,7 @@ source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.p
 while (( $# > 0 )); do
     case ${1} in
     -h | --help)
-        cat << EOF
-Usage:
-    ${0##*/} [OPTION]... RECORD
-
-Optional arguments:
-    -h, --help
-        show this help message and exit
-    -v, --version
-        output version information and exit
-
-Positional arguments:
-    RECORD
-        dns record identifier
-EOF
+        display_help
         shift
         exit
         ;;
@@ -44,13 +65,18 @@ EOF
     esac
 done
 
-RECORD=${1?✗ argument parsing failed: missing positional argument ‘RECORD’}
+RECORD=${1?✗ argument parsing failed: missing argument ‘RECORD’}
 shift
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 curl --fail --location --silent --show-error --request DELETE \
     --header "Authorization: Bearer ${AUTH_TOKEN}" \
diff --git a/bin/domain-inspect b/bin/domain-inspect
--- a/bin/domain-inspect
+++ b/bin/domain-inspect
@@ -1,30 +1,51 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
 
-while (( $# > 0 )); do
-    case ${1} in
-    -h | --help)
-        cat << EOF
-Usage:
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
     ${0##*/} [OPTION]... MANIFEST DOMAIN...
 
-Optional arguments:
+Options:
     -h, --help
         show this help message and exit
     -v, --version
         output version information and exit
 
-Positional arguments:
+Arguments:
     MANIFEST (authority | whois)
         manifest name
     DOMAIN
         domain name to be queried
 EOF
+}
+
+while (( $# > 0 )); do
+    case ${1} in
+    -h | --help)
+        display_help
         shift
         exit
         ;;
@@ -43,17 +64,22 @@ EOF
     esac
 done
 
-: "${1?✗ argument parsing failed: missing positional argument ‘MANIFEST’}"
+: "${1?✗ argument parsing failed: missing argument ‘MANIFEST’}"
 case ${1} in
 authority | whois)
     MANIFEST=${1}
     ;;
 *)
-    echo "✗ argument parsing failed: acceptable values for ‘MANIFEST’ are authority | whois" 1>&2
-    exit 1
+    die "✗ argument parsing failed: acceptable values for ‘MANIFEST’ are authority | whois"
     ;;
 esac
 shift
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 if [ "${MANIFEST}" = authority ]; then
     for i in "$@"; do
diff --git a/bin/git-sync b/bin/git-sync
--- a/bin/git-sync
+++ b/bin/git-sync
@@ -1,10 +1,42 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
+    ${0##*/} [OPTION]...
+
+Options:
+    --force
+        force repository synchronization (default: false)
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+}
 
 FORCE_SYNC=false
 
@@ -15,18 +47,7 @@ while (( $# > 0 )); do
         shift
         ;;
     -h | --help)
-        cat << EOF
-Usage:
-    ${0##*/} [OPTION]...
-
-Optional arguments:
-    --force
-        force repository synchronization (default: false)
-    -h, --help
-        show this help message and exit
-    -v, --version
-        output version information and exit
-EOF
+        display_help
         shift
         exit
         ;;
@@ -46,9 +67,14 @@ EOF
 done
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 if [ "${FORCE_SYNC}" = true ]; then
     url=$(git remote get-url origin)
diff --git a/bin/namecheap-domain-watch b/bin/namecheap-domain-watch
--- a/bin/namecheap-domain-watch
+++ b/bin/namecheap-domain-watch
@@ -1,10 +1,40 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
+    ${0##*/} [OPTION]...
+
+Options:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+}
 
 # shellcheck disable=SC1090
 source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.privacy/namecheap.cfg"
@@ -12,16 +42,7 @@ source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.p
 while (( $# > 0 )); do
     case ${1} in
     -h | --help)
-        cat << EOF
-Usage:
-    ${0##*/} [OPTION]...
-
-Optional arguments:
-    -h, --help
-        show this help message and exit
-    -v, --version
-        output version information and exit
-EOF
+        display_help
         shift
         exit
         ;;
@@ -41,9 +62,14 @@ EOF
 done
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 sleep 15
 
@@ -52,13 +78,11 @@ PUBLIC_IP_ADDRESS=$(dig myip.opendns.com @208.67.222.222 a +short)
 REQUEST_API_METHOD=namecheap.users.getPricing
 
 if [ -z "${CURRENCY_RATE}" ]; then
-    echo '✗ unexpected error: cannot acquire the currency rate' 1>&2
-    exit 1
+    die '✗ unexpected error: cannot acquire the currency rate'
 fi
 
 if [ -z "${PUBLIC_IP_ADDRESS}" ]; then
-    echo '✗ unexpected error: cannot resolve the public ip address' 1>&2
-    exit 1
+    die '✗ unexpected error: cannot resolve the public ip address'
 fi
 
 for i in ${WATCH_LIST}; do
diff --git a/bin/network-dns-hall b/bin/network-dns-hall
--- a/bin/network-dns-hall
+++ b/bin/network-dns-hall
@@ -1,28 +1,49 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
 
-while (( $# > 0 )); do
-    case ${1} in
-    -h | --help)
-        cat << EOF
-Usage:
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
     ${0##*/} [OPTION]... VENDOR
 
-Optional arguments:
+Options:
     -h, --help
         show this help message and exit
     -v, --version
         output version information and exit
 
-Positional arguments:
+Arguments:
     VENDOR (cloudflare | opendns | quad9)
         dns vendor name
 EOF
+}
+
+while (( $# > 0 )); do
+    case ${1} in
+    -h | --help)
+        display_help
         shift
         exit
         ;;
@@ -41,22 +62,26 @@ EOF
     esac
 done
 
-: "${1?✗ argument parsing failed: missing positional argument ‘VENDOR’}"
+: "${1?✗ argument parsing failed: missing argument ‘VENDOR’}"
 case ${1} in
 cloudflare | opendns | quad9)
     VENDOR=${1}
     ;;
 *)
-    echo "✗ argument parsing failed: acceptable values for ‘VENDOR’ are cloudflare | opendns | quad9" 1>&2
-    exit 1
+    die "✗ argument parsing failed: acceptable values for ‘VENDOR’ are cloudflare | opendns | quad9"
     ;;
 esac
 shift
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 case ${VENDOR} in
 cloudflare)
diff --git a/bin/network-dns-perf b/bin/network-dns-perf
--- a/bin/network-dns-perf
+++ b/bin/network-dns-perf
@@ -1,25 +1,34 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
 
-COUNT=64
+die () {
+    warn "${@}"
+    exit 1
+}
 
-while (( $# > 0 )); do
-    case ${1} in
-    -c | --count)
-        COUNT=${2?✗ argument parsing failed: missing parameter for argument ‘${1}’}
-        shift 2
-        ;;
-    -h | --help)
-        cat << EOF
-Usage:
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
     ${0##*/} [OPTION]...
 
-Optional arguments:
+Options:
     -c, --count N
         number of request packets to send (default: 64)
     -h, --help
@@ -27,6 +36,20 @@ Optional arguments:
     -v, --version
         output version information and exit
 EOF
+}
+
+COUNT=64
+
+NAMESERVER=$(awk '/nameserver/ { print $2 }' /etc/resolv.conf)
+
+while (( $# > 0 )); do
+    case ${1} in
+    -c | --count)
+        COUNT=${2?✗ option parsing failed: missing value for argument ‘${1}’}
+        shift 2
+        ;;
+    -h | --help)
+        display_help
         shift
         exit
         ;;
@@ -46,11 +69,14 @@ EOF
 done
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
 
-NAMESERVER=$(awk '/nameserver/ { print $2 }' /etc/resolv.conf)
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 for i in ${NAMESERVER}; do
     fping --count "${COUNT}" --quiet "${i}"
diff --git a/bin/network-inspect-tls b/bin/network-inspect-tls
--- a/bin/network-inspect-tls
+++ b/bin/network-inspect-tls
@@ -1,30 +1,51 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
 
-while (( $# > 0 )); do
-    case ${1} in
-    -h | --help)
-        cat << EOF
-Usage:
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
     ${0##*/} [OPTION]... FILE|URL...
 
-Optional arguments:
+Options:
     -h, --help
         show this help message and exit
     -v, --version
         output version information and exit
 
-Positional arguments:
+Arguments:
     FILE
         input certificate filename
     URL
         website url which employs tls
 EOF
+}
+
+while (( $# > 0 )); do
+    case ${1} in
+    -h | --help)
+        display_help
         shift
         exit
         ;;
@@ -43,8 +64,14 @@ EOF
     esac
 done
 
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
+
 for i in "$@"; do
-    CERT=''
+    CERT=
 
     if [ -e "${i}" ]; then
         if [ -f "${i}" ]; then
@@ -52,23 +79,23 @@ for i in "$@"; do
                 if [ -s "${i}" ]; then
                     CERT=$(cat "${i}" 2> /dev/null)
                 else
-                    echo "✗ file is empty: ‘${i}’" 1>&2
+                    warn "✗ file is empty: ‘${i}’"
                     continue
                 fi
             else
-                echo "✗ read permission not granted: ‘${i}’" 1>&2
+                warn "✗ read permission not granted: ‘${i}’"
                 continue
             fi
         else
-            echo "✗ not a regular file: ‘${i}’" 1>&2
+            warn "✗ not a regular file: ‘${i}’"
             continue
         fi
     else
         CERT=$(openssl s_client -connect "${i}" < /dev/null 2> /dev/null)
     fi
 
-    if [ "${CERT}" = '' ]; then
-        echo "✗ unable to establish tls connection: ‘${i}’" 1>&2
+    if [ -z "${CERT}" ]; then
+        warn "✗ unable to establish tls connection: ‘${i}’"
         continue
     fi
 
diff --git a/bin/site-gen-icon b/bin/site-gen-icon
--- a/bin/site-gen-icon
+++ b/bin/site-gen-icon
@@ -1,28 +1,49 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
 
-while (( $# > 0 )); do
-    case ${1} in
-    -h | --help)
-        cat << EOF
-Usage:
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
     ${0##*/} [OPTION]... INPUT_IMAGE
 
-Optional arguments:
+Options:
     -h, --help
         show this help message and exit
     -v, --version
         output version information and exit
 
-Positional arguments:
+Arguments:
     INPUT_IMAGE
         input image to be converted
 EOF
+}
+
+while (( $# > 0 )); do
+    case ${1} in
+    -h | --help)
+        display_help
         shift
         exit
         ;;
@@ -41,17 +62,21 @@ EOF
     esac
 done
 
-INPUT_IMAGE=${1?✗ argument parsing failed: missing positional argument ‘INPUT_IMAGE’}
+INPUT_IMAGE=${1?✗ argument parsing failed: missing argument ‘INPUT_IMAGE’}
 shift
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
 
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
+
 if [ ! -f "${INPUT_IMAGE}" ]; then
-    echo "✗ not a regular file: ‘${INPUT_IMAGE}’" 1>&2
-    exit 1
+    die "✗ not a regular file: ‘${INPUT_IMAGE}’"
 fi
 
 convert -background transparent "${INPUT_IMAGE}" -define icon:auto-resize=16,32 favicon.ico
diff --git a/bin/ssh-remote-execute b/bin/ssh-remote-execute
--- a/bin/ssh-remote-execute
+++ b/bin/ssh-remote-execute
@@ -1,28 +1,49 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
 
-while (( $# > 0 )); do
-    case ${1} in
-    -h | --help)
-        cat << EOF
-Usage:
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
     ${0##*/} [OPTION]... HOST
 
-Optional arguments:
+Options:
     -h, --help
         show this help message and exit
     -v, --version
         output version information and exit
 
-Positional arguments:
+Arguments:
     HOST
         ssh host name
 EOF
+}
+
+while (( $# > 0 )); do
+    case ${1} in
+    -h | --help)
+        display_help
         shift
         exit
         ;;
@@ -41,13 +62,18 @@ EOF
     esac
 done
 
-HOST=${1?✗ argument parsing failed: missing positional argument ‘HOST’}
+HOST=${1?✗ argument parsing failed: missing argument ‘HOST’}
 shift
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 ssh -T "${HOST}" << 'EOF'
     for i in {1..8}; do
diff --git a/bin/swaks-push-message b/bin/swaks-push-message
--- a/bin/swaks-push-message
+++ b/bin/swaks-push-message
@@ -1,10 +1,44 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
+    ${0##*/} [OPTION]... COMMAND...
+
+Options:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+
+Arguments:
+    COMMAND
+        command to be executed within command substitution
+EOF
+}
 
 # shellcheck disable=SC1090
 source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.privacy/smtp.cfg"
@@ -12,20 +46,7 @@ source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.p
 while (( $# > 0 )); do
     case ${1} in
     -h | --help)
-        cat << EOF
-Usage:
-    ${0##*/} [OPTION]... COMMAND...
-
-Optional arguments:
-    -h, --help
-        show this help message and exit
-    -v, --version
-        output version information and exit
-
-Positional arguments:
-    COMMAND
-        command to be executed within command substitution
-EOF
+        display_help
         shift
         exit
         ;;
@@ -45,9 +66,14 @@ EOF
 done
 
 if (( $# == 0 )); then
-    echo "✗ argument parsing failed: missing positional argument ‘COMMAND’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: missing argument ‘COMMAND’"
 fi
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 # Swiss Army Knife SMTP
 
diff --git a/bin/zulip-clean-stream b/bin/zulip-clean-stream
--- a/bin/zulip-clean-stream
+++ b/bin/zulip-clean-stream
@@ -1,29 +1,50 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
 
-# shellcheck disable=SC1090
-source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.privacy/zulip.cfg"
+die () {
+    warn "${@}"
+    exit 1
+}
 
-: "${MESSAGE_RETENTION:=86400}"
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
 
-while (( $# > 0 )); do
-    case ${1} in
-    -h | --help)
-        cat << EOF
-Usage:
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
     ${0##*/} [OPTION]...
 
-Optional arguments:
+Options:
     -h, --help
         show this help message and exit
     -v, --version
         output version information and exit
 EOF
+}
+
+: "${MESSAGE_RETENTION:=86400}"
+
+# shellcheck disable=SC1090
+source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.privacy/zulip.cfg"
+
+while (( $# > 0 )); do
+    case ${1} in
+    -h | --help)
+        display_help
         shift
         exit
         ;;
@@ -45,9 +66,14 @@ done
 export MESSAGE_RETENTION
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 list=$(curl --fail --location --silent --show-error --request GET \
     --get \
diff --git a/bin/zulip-push-message b/bin/zulip-push-message
--- a/bin/zulip-push-message
+++ b/bin/zulip-push-message
@@ -1,10 +1,40 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
+
+display_help () {
+    cat << EOF
+Synopsis:
+    ${0##*/} [OPTION]...
+
+Options:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+}
 
 # shellcheck disable=SC1090
 source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.privacy/zulip.cfg"
@@ -12,16 +42,7 @@ source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.p
 while (( $# > 0 )); do
     case ${1} in
     -h | --help)
-        cat << EOF
-Usage:
-    ${0##*/} [OPTION]...
-
-Optional arguments:
-    -h, --help
-        show this help message and exit
-    -v, --version
-        output version information and exit
-EOF
+        display_help
         shift
         exit
         ;;
@@ -41,9 +62,14 @@ EOF
 done
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 TEXT=
 while IFS= read -r LINE; do
diff --git a/sbin/docker-create-cluster b/sbin/docker-create-cluster
--- a/sbin/docker-create-cluster
+++ b/sbin/docker-create-cluster
@@ -1,15 +1,44 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
 
 if (( EUID != 0 )); then
-    echo '✗ This script must be run as root' 1>&2
-    exit 1
+    die '✗ This script must be run as root'
 fi
+
+display_help () {
+    cat << EOF
+Synopsis:
+    ${0##*/} [OPTION]...
+
+Options:
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+}
 
 CLUSTER_GATEWAY=172.24.0.1
 CLUSTER_SUBNET=172.24.0.0/16
@@ -20,16 +49,7 @@ source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.p
 while (( $# > 0 )); do
     case ${1} in
     -h | --help)
-        cat << EOF
-Usage:
-    ${0##*/} [OPTION]...
-
-Optional arguments:
-    -h, --help
-        show this help message and exit
-    -v, --version
-        output version information and exit
-EOF
+        display_help
         shift
         exit
         ;;
@@ -49,12 +69,17 @@ EOF
 done
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
 
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
+
 docker network create \
-    --driver=bridge \
-    --gateway="${CLUSTER_GATEWAY}" \
-    --subnet="${CLUSTER_SUBNET}" \
+    --driver bridge \
+    --gateway "${CLUSTER_GATEWAY}" \
+    --subnet "${CLUSTER_SUBNET}" \
     cluster
diff --git a/sbin/docker-deploy-coredns b/sbin/docker-deploy-coredns
--- a/sbin/docker-deploy-coredns
+++ b/sbin/docker-deploy-coredns
@@ -1,29 +1,51 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
 
 if (( EUID != 0 )); then
-    echo '✗ This script must be run as root' 1>&2
-    exit 1
+    die '✗ This script must be run as root'
 fi
 
-while (( $# > 0 )); do
-    case ${1} in
-    -h | --help)
-        cat << EOF
-Usage:
+display_help () {
+    cat << EOF
+Synopsis:
     ${0##*/} [OPTION]...
 
-Optional arguments:
+Options:
     -h, --help
         show this help message and exit
     -v, --version
         output version information and exit
 EOF
+}
+
+NAME=coredns
+
+while (( $# > 0 )); do
+    case ${1} in
+    -h | --help)
+        display_help
         shift
         exit
         ;;
@@ -43,11 +65,14 @@ EOF
 done
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
 
-NAME=coredns
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 if [ -n "$(docker container ls --all --filter name='^/'${NAME}'$' --format '.')" ]; then
     docker container stop "${NAME}"
diff --git a/sbin/letsencrypt-provision b/sbin/letsencrypt-provision
--- a/sbin/letsencrypt-provision
+++ b/sbin/letsencrypt-provision
@@ -1,35 +1,55 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
 
 if (( EUID != 0 )); then
-    echo '✗ This script must be run as root' 1>&2
-    exit 1
+    die '✗ This script must be run as root'
 fi
 
-while (( $# > 0 )); do
-    case ${1} in
-    -h | --help)
-        cat << EOF
-Usage:
+display_help () {
+    cat << EOF
+Synopsis:
     ${0##*/} [OPTION]... MODE DOMAIN
 
-Optional arguments:
+Options:
     -h, --help
         show this help message and exit
     -v, --version
         output version information and exit
 
-Positional arguments:
+Arguments:
     MODE (request | revoke)
         certificate provision mode
     DOMAIN
         domain name to apply
 EOF
+}
+
+while (( $# > 0 )); do
+    case ${1} in
+    -h | --help)
+        display_help
         shift
         exit
         ;;
@@ -48,23 +68,27 @@ EOF
     esac
 done
 
-: "${1?✗ argument parsing failed: missing positional argument ‘MODE’}"
+: "${1?✗ argument parsing failed: missing argument ‘MODE’}"
 case ${1} in
 request | revoke)
     MODE=${1}
     ;;
 *)
-    echo "✗ argument parsing failed: acceptable values for ‘MODE’ are request | revoke" 1>&2
-    exit 1
+    die "✗ argument parsing failed: acceptable values for ‘MODE’ are request | revoke"
     ;;
 esac
-DOMAIN=${2?✗ argument parsing failed: missing positional argument ‘DOMAIN’}
+DOMAIN=${2?✗ argument parsing failed: missing argument ‘DOMAIN’}
 shift 2
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 if [ "${MODE}" = request ]; then
     certbot certonly \
diff --git a/sbin/sys-boot b/sbin/sys-boot
--- a/sbin/sys-boot
+++ b/sbin/sys-boot
@@ -1,29 +1,49 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
 
 if (( EUID != 0 )); then
-    echo '✗ This script must be run as root' 1>&2
-    exit 1
+    die '✗ This script must be run as root'
 fi
 
-while (( $# > 0 )); do
-    case ${1} in
-    -h | --help)
-        cat << EOF
-Usage:
+display_help () {
+    cat << EOF
+Synopsis:
     ${0##*/} [OPTION]...
 
-Optional arguments:
+Options:
     -h, --help
         show this help message and exit
     -v, --version
         output version information and exit
 EOF
+}
+
+while (( $# > 0 )); do
+    case ${1} in
+    -h | --help)
+        display_help
         shift
         exit
         ;;
@@ -43,13 +63,17 @@ EOF
 done
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
 
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
+
 if [ "${OSTYPE}" != linux-gnu ]; then
-    echo "✗ unknown os type: ‘${OSTYPE}’" 1>&2
-    exit 1
+    die "✗ unknown os type: ‘${OSTYPE}’"
 fi
 
 # shellcheck disable=SC1090
@@ -78,7 +102,6 @@ opensuse*)
     grub2-mkconfig --output /boot/grub2/grub.cfg
     ;;
 *)
-    echo "✗ unknown distro: ‘${DISTRO}’" 1>&2
-    exit 1
+    die "✗ unknown distro: ‘${DISTRO}’"
     ;;
 esac
diff --git a/sbin/sys-quick b/sbin/sys-quick
--- a/sbin/sys-quick
+++ b/sbin/sys-quick
@@ -1,33 +1,53 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
 
 if (( EUID != 0 )); then
-    echo '✗ This script must be run as root' 1>&2
-    exit 1
+    die '✗ This script must be run as root'
 fi
 
-while (( $# > 0 )); do
-    case ${1} in
-    -h | --help)
-        cat << EOF
-Usage:
+display_help () {
+    cat << EOF
+Synopsis:
     ${0##*/} [OPTION]... ALIAS
 
-Optional arguments:
+Options:
     -h, --help
         show this help message and exit
     -v, --version
         output version information and exit
 
-Positional arguments:
+Arguments:
     ALIAS (netstat | iptables | ip6tables | ss)
         diagnostic launcher name
 EOF
+}
+
+while (( $# > 0 )); do
+    case ${1} in
+    -h | --help)
+        display_help
         shift
         exit
         ;;
@@ -46,22 +66,26 @@ EOF
     esac
 done
 
-: "${1?✗ argument parsing failed: missing positional argument ‘ALIAS’}"
+: "${1?✗ argument parsing failed: missing argument ‘ALIAS’}"
 case ${1} in
 netstat | iptables | ip6tables | ss)
     ALIAS=${1}
     ;;
 *)
-    echo "✗ argument parsing failed: acceptable values for ‘ALIAS’ are netstat | iptables | ip6tables | ss" 1>&2
-    exit 1
+    die "✗ argument parsing failed: acceptable values for ‘ALIAS’ are netstat | iptables | ip6tables | ss"
     ;;
 esac
 shift
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
+
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
 
 separator=----------------------------------------------------------------
 
diff --git a/sbin/sys-sync b/sbin/sys-sync
--- a/sbin/sys-sync
+++ b/sbin/sys-sync
@@ -1,15 +1,46 @@
 #!/bin/bash
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
-trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR
+warn () {
+    if (( $# > 0 )); then
+        echo "${@}" 1>&2
+    fi
+}
+
+die () {
+    warn "${@}"
+    exit 1
+}
+
+notify () {
+    local code=$?
+    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
+}
+
+trap notify ERR
 
 if (( EUID != 0 )); then
-    echo '✗ This script must be run as root' 1>&2
-    exit 1
+    die '✗ This script must be run as root'
 fi
+
+display_help () {
+    cat << EOF
+Synopsis:
+    ${0##*/} [OPTION]...
+
+Options:
+    -f, --force
+        force synchronization of package metadata (default: false)
+    -h, --help
+        show this help message and exit
+    -v, --version
+        output version information and exit
+EOF
+}
 
 FORCE_SYNC=false
 
@@ -20,18 +51,7 @@ while (( $# > 0 )); do
         shift
         ;;
     -h | --help)
-        cat << EOF
-Usage:
-    ${0##*/} [OPTION]...
-
-Optional arguments:
-    -f, --force
-        force synchronization of package metadata (default: false)
-    -h, --help
-        show this help message and exit
-    -v, --version
-        output version information and exit
-EOF
+        display_help
         shift
         exit
         ;;
@@ -51,13 +71,17 @@ EOF
 done
 
 if (( $# > 0 )); then
-    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
-    exit 1
+    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
 fi
 
+clean_up () {
+    true
+}
+
+trap clean_up EXIT
+
 if [ "${OSTYPE}" != linux-gnu ]; then
-    echo "✗ unknown os type: ‘${OSTYPE}’" 1>&2
-    exit 1
+    die "✗ unknown os type: ‘${OSTYPE}’"
 fi
 
 # shellcheck disable=SC1090
@@ -104,7 +128,6 @@ opensuse*)
     zypper clean
     ;;
 *)
-    echo "✗ unknown distro: ‘${DISTRO}’" 1>&2
-    exit 1
+    die "✗ unknown distro: ‘${DISTRO}’"
     ;;
 esac
